### ISSUE TITLE
Cannot find databinding

### ISSUE THREAD

**Issue by rgocal** [iammert/MultiSearchView#2]
I tried implementing this library in my project and it compiled correctly but crashed when the app started and said something about not finding a databinding class.

ClassNotFoundException: Didn't find class "androidx.databinding.DataBinderMapperImpl"

**Comment by saadheikh** [comment]
not working 
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.0.

**Comment by mertceyhan** [comment]
I couldn't repeat this error. Could you update the library with implementation 'com.github.iammert:MultiSearchView:0.3'.
We migrated the project to androidx, the error could be related to androidx. @rgocal

**Comment by rgocal** [comment]
Il have to try a sample project sometime

**Comment by rgocal** [comment]
ok, its working without any problems now. well done
