### ISSUE TITLE
java.lang.NoClassDefFoundError / java.lang.reflect.InvocationTargetException /android.view.InflateException

### ISSUE THREAD

**Issue by itzkou** [iammert/MultiSearchView#8]
![image](https://user-images.githubusercontent.com/56657738/89236507-b1c79f00-d5e8-11ea-90c9-ca03791afd1a.png)

![image](https://user-images.githubusercontent.com/56657738/89236564-d9b70280-d5e8-11ea-8c54-ab542b9eb1e2.png)

**Comment by mertceyhan** [comment]
Can you share some information about the device and the project such as device api level, project minSdk? @itzkou

**Comment by itzkou** [comment]
First of all this library seems beautiful as hell !!
I am using a huawei Y7 2019   "DUB LX1 " 
👾
Gradle Plugin Version  4.0.0
Gradle Version 6.1.1
👾 this is a snippet of my gradle module app
android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.kou.seekmake"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
   
}

**Comment by mertceyhan** [comment]
I couldn't repeat this error. Could you update the library with `implementation 'com.github.iammert:MultiSearchView:0.3'`. 
We migrated the project to androidx, the error could be related to androidx. @itzkou

**Comment by itzkou** [comment]
yes exactly mert it's related to DataBinding , I have an issue generating Databinding class so that's my main problem thanks for your support
